export const APP_ROUTE_METADATA = [
  {
    path: "/dashboard",
    label: "Dashboard",
    icon: "bi-grid-1x2-fill",
    group: "Overview",
    showInSidebar: true,
  },
  {
    path: "/pos",
    label: "Point of Sale",
    icon: "bi-calculator",
    group: "Overview",
    showInSidebar: true,
  },
  {
    path: "/orders",
    label: "Order History",
    icon: "bi-clock-history",
    group: "Sales & Reports",
    showInSidebar: true,
  },
  {
    path: "/reports/sales",
    label: "Sales Report",
    icon: "bi-graph-up-arrow",
    group: "Sales & Reports",
    showInSidebar: true,
  },
  {
    path: "/expenses",
    label: "Expense Tracking",
    icon: "bi-wallet2",
    group: "Sales & Reports",
    showInSidebar: true,
  },
  {
    path: "/expenses/archive",
    label: "Expense Archive",
    parentPath: "/expenses",
    group: "Sales & Reports",
    showInSidebar: false,
  },
  {
    path: "/inventory",
    label: "Inventory Management",
    icon: "bi-box-seam",
    group: "Inventory & Menu",
    showInSidebar: true,
  },
  {
    path: "/inventory/archive",
    label: "Inventory Archive",
    parentPath: "/inventory",
    group: "Inventory & Menu",
    showInSidebar: false,
  },
  {
    path: "/inventory/valuation",
    label: "Inventory Valuation",
    icon: "bi-clipboard-data",
    group: "Inventory & Menu",
    showInSidebar: true,
  },
  {
    path: "/inventory/audit",
    label: "Inventory Audit Log",
    icon: "bi-journal-check",
    group: "Inventory & Menu",
    showInSidebar: true,
  },
  {
    path: "/menu",
    label: "Menu Management",
    icon: "bi-journal-richtext",
    group: "Inventory & Menu",
    showInSidebar: true,
  },
  {
    path: "/menu/addons",
    label: "Manage Add-ons",
    group: "Inventory & Menu",
    showInSidebar: false,
  },
  {
    path: "/menu/archive",
    label: "Menu Archive",
    parentPath: "/menu",
    group: "Inventory & Menu",
    showInSidebar: false,
  },
  {
    path: "/employees",
    label: "Employee Management",
    icon: "bi-people",
    group: "Administration",
    showInSidebar: true,
  },
  {
    path: "/profile",
    label: "Profile",
    group: "Administration",
    showInSidebar: false,
  },
];

export const SIDEBAR_GROUP_ORDER = [
  "Overview",
  "Sales & Reports",
  "Inventory & Menu",
  "Administration",
];
