export const printingStrategies = [
  {
    id: "browser", title: "Browser receipt", icon: "bi-printer", status: "Ready to try",
    summary: "Use the familiar print window. Start here as a comparison.",
    how: "The website prepares a receipt; your browser and installed printer driver send it.",
    needs: "A configured printer or Save as PDF. Android may need a print-service app.",
    settings: "Current receipt width: 58 mm. Match the paper width, use 100% scale, and turn off browser headers/footers where available.",
    check: "Look for the first and last lines, readable amounts, and no blank first page. A closed print window does not prove paper came out.",
    button: "Open test receipt", ready: true,
  },
  {
    id: "text", title: "Text commands", icon: "bi-code-square", status: "Export ready",
    summary: "Send text and alignment instructions instead of a webpage.",
    how: "An encoder translates sample receipt data into the printer's receipt language, called ESC/POS.",
    needs: "For export: this page only. For the next test: your PC receipt emulator.",
    settings: "Fixed 32-column ESC/POS text. Accents become plain letters; currency uses PHP. No cutter or drawer commands.",
    check: "This downloads a command file, not a PDF. The sample preview shows content, not the exact encoded layout. Emulator delivery is the next step.",
    button: "Download test commands", ready: true,
    link: "https://github.com/at-point-of-sale/ReceiptPrinterEncoder", linkLabel: "Encoder documentation",
  },
  {
    id: "image", title: "Image commands", icon: "bi-image", status: "Planned",
    summary: "Turn the receipt into a black-and-white image before sending it.",
    how: "We draw the receipt, then encode its pixels as printer commands. This is a different test from printing a PDF.",
    needs: "An image encoder and a printer or emulator that supports its image commands.",
    settings: "Use the printer's printable width in dots, not a guessed paper width. Compare sharpness and output length.",
    check: "Check accents, the peso sign, and long receipts. An image can help with fonts, but cannot fix the wrong connection or printer mode.",
    button: "Image encoding not connected yet", ready: false,
  },
  {
    id: "rawbt", title: "Android / RawBT", icon: "bi-phone", status: "Ready for Android test",
    summary: "Let an Android helper app deliver the print data over Bluetooth.",
    how: "The button asks Android to open RawBT with this sample's ESC/POS text commands. No manual file download or PowerShell is needed.",
    needs: "Chrome on Android, RawBT installed, Bluetooth permission, and a compatible paired printer. Not an iPhone or PC method.",
    settings: "Choose the physical printer and a profile that passes prepared ESC/POS bytes through. This is a 32-column receipt test, not sticker commands. Confirm receipt-mode compatibility, actual paper, and RawBT licensing before sending.",
    check: "Start with Simple receipt. This may print immediately on RawBT's selected printer. No cutter or drawer commands are included. The browser cannot confirm installation, cancellation, or paper output. Check the queue before retrying; physical compatibility remains unverified.",
    button: "Print via RawBT", ready: true,
    link: "https://rawbt.ru/index.html", linkLabel: "RawBT documentation",
  },
  {
    id: "label", title: "Cup sticker label", icon: "bi-tag", status: "Preview only",
    summary: "A small sticker with the drink, size, add-ons, and order number.",
    how: "This is a separate layout, not a shrunken receipt. Label-mode printers may use TSPL, a different command language.",
    needs: "Measured sticker width, height, and gap, plus a label-compatible printer and delivery method.",
    settings: "The sizes below are examples, not detected printer settings. Measure the actual sticker before choosing a final size.",
    check: "Preview is available now. Command generation and label feeding are not connected, and the receipt emulator does not verify TSPL labels.",
    button: "Preview sample label", ready: true,
  },
  {
    id: "qz", title: "PC / QZ Tray", icon: "bi-pc-display", status: "Planned",
    summary: "Use a desktop helper to send commands without the browser print window.",
    how: "The web page connects to QZ Tray installed on the same computer. QZ delivers the job to the chosen printer or emulator.",
    needs: "Windows, macOS, or Linux with QZ Tray installed. This is our desktop route, not a native Android helper.",
    settings: "Choose the exact local printer and allow the connection prompt. Free use has prompts; silent printing needs certificate setup.",
    check: "Try command delivery to the PC emulator first. Do not auto-retry an uncertain result; the original job may have printed.",
    button: "QZ delivery not connected yet", ready: false,
    link: "https://qz.io/docs/getting-started", linkLabel: "QZ Tray documentation",
  },
];
