// Three delivery methods. Text/image are receipt formats inside the helper methods.
export const printingStrategies = [
  {
    id: "browser", title: "Browser / POS receipt", icon: "bi-printer", status: "Browser method",
    summary: "Print using the familiar browser print window.",
    how: "Use this with a printer available in your device's print menu. This is the same receipt window used by the POS.",
    needs: "A configured printer and driver or supported Android print service. Save as PDF checks the layout only.",
    tutorial: [
      { title: "Turn on the printer", text: "Ask the cafe staff for permission. Check that paper is loaded and the cover is closed. Do not reset the printer or change its receipt/label mode." },
      { title: "Connect it to your device", text: "On PC, use the cafe's configured USB or network connection. For Bluetooth, turn it on and pair the printer first. On Android, open Settings → Bluetooth → Pair new device and select the printer confirmed by the staff. Menu labels vary by phone." },
      { title: "Check that printing is available", text: "On Windows, look in Settings → Bluetooth & devices → Printers & scanners; the correct driver must be installed. Android needs a compatible print service. Bluetooth pairing alone does not make a printer appear in the browser's print menu." },
      { title: "Open the sample receipt", text: "Keep Simple receipt selected below. In the preview panel, click Open test receipt, then Print Receipt in the modal. This opens the browser print window." },
      { title: "Select the printer and paper", text: "Choose the actual printer under Destination, not Save as PDF. This browser layout is designed for 58 mm paper. Match the driver's paper width, use Portrait, Margins: None and Scale: 100%, and turn off headers/footers when available. If the paper is another size, ask for the correct layout rather than guessing." },
      { title: "Print once and inspect the paper", text: "Click Print once. Check the cafe name, all items, total PHP 320.00 and the closing thank-you message. Look for clipped text or a blank first sheet." },
      { title: "If nothing prints", text: "Check the system printer queue before retrying. If the printer is missing from Destination, this route is not configured yet. On Android, use the RawBT guide; on PC, use the QZ guide. First check that the previous job is not still waiting." },
    ],
    check: "A PDF preview or a closed print window is not proof of paper output. Check the previous queue before changing methods.",
    links: [{ label: "Android Bluetooth pairing help", url: "https://support.google.com/android/answer/9417604" }],
  },
  {
    id: "rawbt", title: "Android / RawBT", icon: "bi-phone", status: "Android method",
    summary: "Send the receipt through RawBT to a paired printer.",
    how: "Your Android phone opens RawBT with the prepared receipt. RawBT handles the printer connection; the website does not connect directly to Bluetooth.",
    needs: "Android Chrome, RawBT, Bluetooth access, and a paired printer that accepts ESC/POS receipt commands. Not an iPhone or PC method.",
    tutorial: [
      { title: "Turn on the printer and Bluetooth", text: "Check paper and close the printer cover. Open the Android phone's Settings and turn Bluetooth on. Stay near the printer. Do not change the cafe's printer mode or disconnect another cashier's active device without permission." },
      { title: "Pair the correct printer", text: "In Bluetooth settings, tap Pair new device or Available devices. Choose the printer confirmed by the cafe staff and accept pairing. If a PIN is requested, ask the staff or use the printer manual. Android menu names vary." },
      { title: "Install and open RawBT", text: "Use the Google Play link below. Open RawBT and allow its Bluetooth / Nearby devices permissions. Review any free-version or licensing notice before testing." },
      { title: "Choose the printer inside RawBT", text: "In RawBT's printer or connection settings, choose Bluetooth and the paired printer. Use a compatible ESC/POS profile that sends our prepared commands unchanged. Setting names vary by RawBT version; do not select a different printer by guesswork." },
      { title: "Check RawBT itself first", text: "Use RawBT's own test-print option, if available, once. If it cannot print, fix pairing, permission, paper or printer selection before testing the website. Ask the staff if receipt-command support is uncertain." },
      { title: "Open this page in Android Chrome", text: "Load the updated /print-test page online first. Choose Android / RawBT and keep Simple receipt selected. Image is the default. Check the displayed width; Advanced options lets you match the printer's documented printable dots. The 384/576 choices are not automatic paper detection." },
      { title: "Prepare and print once", text: "Click Prepare receipt preview. Review the logo, items and amounts, then click Print via RawBT once. If Android asks which app to use, choose RawBT. It may print immediately using the printer selected inside RawBT." },
      { title: "Inspect before trying again", text: "Look for the logo, total PHP 320.00 and END OF TEST RECEIPT. A handoff message is not proof of paper output. If delayed or blank, check RawBT's queue first. Only then use the queue-check button to unlock another test. Text fallback and another image command are in Advanced options." },
    ],
    check: "RawBT must know which printer to use. No file download or terminal command is needed. The lab sends no cutter or cash-drawer command.",
    links: [
      { label: "Install RawBT from Google Play", url: "https://play.google.com/store/apps/details?id=ru.a402d.rawbtprinter" },
      { label: "Android Bluetooth pairing help", url: "https://support.google.com/android/answer/9417604" },
    ],
  },
  {
    id: "qz", title: "PC / QZ Tray", icon: "bi-pc-display", status: "Desktop method",
    summary: "Send the receipt through QZ Tray on this computer.",
    how: "The website talks to QZ Tray on this PC. QZ delivers the commands to an installed printer, or to the PC emulator when no printer is available.",
    needs: "QZ Tray desktop app and a compatible installed receipt printer. For practice without hardware, use the receipt emulator on this PC.",
    tutorial: [
      { title: "Prepare a printer or emulator", text: "For hardware, turn on the printer, check paper and use the cafe's configured USB/network connection. For Bluetooth, pair it in Windows first. It must also appear in Windows Printers & scanners with the correct driver; pairing alone is not enough. Do not change the cafe's driver or printer mode without permission." },
      { title: "Install and open QZ Tray", text: "Use the download link below. Install and start QZ Tray on the same computer where this page is open, then keep it running. Android RawBT is not needed." },
      { title: "Choose where to send", text: "Keep PC emulator selected to practice without paper. Start the emulator's TCP listener at 127.0.0.1, port 9100, and clear its preview. At the cafe, choose Installed printer instead. Never send to an unconfirmed printer." },
      { title: "Connect this page to QZ", text: "Click Connect QZ Tray. Approve only this site's connection prompt and allow local-connection permission if your browser asks. Wait for Connected. This does not print. Do not disable browser security to bypass an error." },
      { title: "Select the printer if using hardware", text: "Skip this for the emulator. Click Load / refresh printers and choose the exact receipt printer. It must support ESC/POS receipt commands and raw jobs through its driver. Do not choose Microsoft Print to PDF." },
      { title: "Prepare the preview", text: "Keep Simple receipt selected below the guide. Image is the default. Check the displayed width; use Advanced options to match the printer's documented printable dots if necessary. Click Prepare receipt preview and review the logo and amounts. Preparation does not print." },
      { title: "Send once and check output", text: "Click Send via QZ Tray. Approve only your requested sample job if prompted. Check the emulator or paper for the logo, total PHP 320.00 and END OF TEST RECEIPT. Job acceptance is not proof of physical printing." },
      { title: "Finish safely", text: "Before another attempt, check output and clear unwanted queued jobs, then click the queue-check button. Text is available in Advanced options. When finished, click Disconnect; disconnecting does not cancel an already submitted job." },
    ],
    check: "The emulator checks commands, not hardware. Keep QZ permission prompts enabled; there is no silent-printing certificate or automatic retry.",
    links: [
      { label: "Download QZ Tray desktop app", url: "https://qz.io/download/" },
      { label: "QZ Windows raw-printer setup reference", url: "https://qz.io/docs/setting-up-a-raw-printer-in-windows" },
    ],
  },
];
