<?php

namespace App\Http\Controllers\Api\PosManagement\Orchestrators;

use App\Http\Controllers\Api\InventoryManagement\AuditLogs\InventoryAuditLogController;
use App\Http\Controllers\Api\InventoryManagement\Batches\InventorySaleDeductionController;
use App\Http\Controllers\Api\OrderManagement\OrderItemAddons\OrderItemAddonController;
use App\Http\Controllers\Api\OrderManagement\OrderItems\OrderItemController;
use App\Http\Controllers\Api\OrderManagement\Orders\OrderController;
use App\Http\Controllers\Controller;
use App\Models\OrderManagement\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\UniqueConstraintViolationException;

class CheckoutOrchestrator extends Controller
{
    public function store(Request $request)
    {
        $clientTransactionId = $request->header('Idempotency-Key');

        // Return the saved order when the same checkout is retried.
        if ($clientTransactionId) {
            $existingOrder = Order::where(
                'client_transaction_id',
                $clientTransactionId
            )->first();

            if ($existingOrder)
                return $this->existingOrderResponse($existingOrder);
        }

        try {
            $order = DB::transaction(function () use ($request, $clientTransactionId) {
                $orderData = $request->input('order');
                $itemsData = $request->input('items', []);

                // Create the main receipt.
                $order = app(OrderController::class)->store([
                    'order_number' => $orderData['order_number'] ?? 'ONLINE-' . (string) Str::uuid(),
                    'cashier_id' => $request->user()->id,
                    'client_transaction_id' => $clientTransactionId,
                    'order_datetime' => now('Asia/Manila'),
                    'order_source' => $orderData['order_source'],
                    'payment_method' => $orderData['payment_method'],
                    'discount_type' => $orderData['discount_type'] ?? 'None',
                    'subtotal' => $orderData['subtotal'],
                    'discount_amount' => $orderData['discount_amount'] ?? 0,
                    'total' => $orderData['total'],
                    'amount_paid' => $orderData['amount_paid'],
                    'change_amount' => $orderData['change_amount'],
                ]);

                // Get the final number generated by the database trigger.
                $order->refresh();

                foreach ($itemsData as $itemData) {
                    $orderItem = app(OrderItemController::class)->store($itemData, $order->id);

                    app(OrderItemAddonController::class)->storeMany(
                        $itemData['addons'] ?? [],
                        $orderItem->id
                    );
                }

                $transactionReference = (string) Str::uuid();

                // Stable ordering reduces database deadlock risk.
                $inventoryDeductions = collect($request->input('inventory_deductions', []))
                    ->sortBy('inventory_item_id')
                    ->values();

                foreach ($inventoryDeductions as $deductionData) {
                    $result = app(InventorySaleDeductionController::class)->deduct(
                        $deductionData['inventory_item_id'],
                        (float) $deductionData['quantity']
                    );

                    $runningStock = $result['stock_before'];

                    // Create one Audit Log for every affected batch.
                    foreach ($result['deductions'] as $batchDeduction) {
                        $stockBefore = $runningStock;
                        $stockAfter =
                            $stockBefore -
                            $batchDeduction['quantity'];

                        app(InventoryAuditLogController::class)->store([
                            'inventory_item_id' => $deductionData['inventory_item_id'],
                            'batch_id' => $batchDeduction['batch_id'],
                            'transaction_reference' => $transactionReference,
                            'action' => 'POS Sale',
                            'source' => 'POS Checkout',
                            'quantity_change' => -abs($batchDeduction['quantity']),
                            'stock_before' => $stockBefore,
                            'stock_after' => $stockAfter,
                            'reason_reference' => 'Sold in Order #' . $order->order_number,
                            'performed_by' => $request->user()->id,
                        ]);

                        $runningStock = $stockAfter;
                    }
                }

                return $order->load([
                    'cashier',
                    'order_items.menu_item',
                    'order_items.variant',
                    'order_items.addons.addon',
                ]);
            });
        } catch (UniqueConstraintViolationException $exception) {
            // Handles two identical requests arriving together.
            if (!$clientTransactionId)
                throw $exception;

            $existingOrder = Order::where(
                'client_transaction_id',
                $clientTransactionId
            )->first();

            if (!$existingOrder)
                throw $exception;

            return $this->existingOrderResponse($existingOrder);
        }

        return response()->json([
            'message' => 'Order processed successfully.',
            'order' => $order,
            'already_processed' => false,
        ], 201);
    }

    private function existingOrderResponse(Order $order)
    {
        return response()->json([
            'message' => 'Order was already processed.',
            'order' => $order->load([
                'cashier',
                'order_items.menu_item',
                'order_items.variant',
                'order_items.addons.addon',
            ]),
            'already_processed' => true,
        ], 200);
    }
}
